### ISSUE TITLE
The content in the Microsoft Programmer's Library CD-ROM (1988) cannot be read normally on the emulator of windows 3.1

### ISSUE THREAD

**Issue by roundlessx** [jeffpar/pcjs#12]
In fact, Jeff, this problem occurred on the[Microsoft Programmer's Library CD-ROM (1988)]( https://www.pcjs.org/blog/2019/05/31/ )page in PCjs.org.

The following is the problem log:

The site where the problem occurred:
["Microsoft Programmer's Library CD-ROM (1988)"](https://www.pcjs.org/blog/2019/05/31/)

Prerequisite: 
I want to view the contents of the Microsoft Programmer's Library CD-ROM as described on the site. I installed the Microsoft Programmer's Library CD-ROM to _C:\mslib_.

Unsolvable difficulties:
After running _C:\mslib\msl.exe_, it displays
![6](https://user-images.githubusercontent.com/45331619/106389989-2a38dc80-6421-11eb-98fd-736c5e857f4d.PNG)

At this point, no matter I press any key on the keyboard, the program cannot continue to run unless I exit the program with Ctrl+C.

My OS: 
windows 10

My Browser:
Chrome

Problem reproduction process:

1. Enter the The site where the problem occurred - [Microsoft Programmer's Library CD-ROM (1988)](https://www.pcjs.org/blog/2019/05/31/).
2. In the emulator, under win 3.1, load Programmer’s Library 1.0 (1988) on the CD-ROM displayed as Disk D.
3. Open the simulator, run _D:\setup.exe_, install Microsoft Programmer's Library to _C:\mslib_ step-by-step following the _D:\setup.exe_ shows
4. After installation, Run _C:\mslib\msl.exe_     <---(Microsoft Programmer's Library installed above)
5. After running _C:\mslib\msl.exe_, it displays
![6](https://user-images.githubusercontent.com/45331619/106389954-0a091d80-6421-11eb-9d5f-d6c458a4d571.PNG)

_The screenshot of the installation process is in the attachment, and the file name of the attachment represents its order_

![1](https://user-images.githubusercontent.com/45331619/106389440-4c7d2b00-641e-11eb-8374-c9c6d7315dd3.PNG)
![2](https://user-images.githubusercontent.com/45331619/106389456-5bfc7400-641e-11eb-91d7-f105b4d9601f.PNG)
![3](https://user-images.githubusercontent.com/45331619/106389462-61f25500-641e-11eb-8e2f-9c8434656310.PNG)
press “H”
![4](https://user-images.githubusercontent.com/45331619/106389467-64ed4580-641e-11eb-9130-885df74a8777.PNG)
press “Y”
![5](https://user-images.githubusercontent.com/45331619/106389469-674f9f80-641e-11eb-9187-7fd0a985a271.PNG)

After I encountered this problem, I installed win 3.1 via dosbox on my pc, but I couldn't install Microsoft Programmer's Library because it was not compatible with my CD-ROM. Few people on other computer forums know about pcjs.org and they cannot answer questions. At first I suspected that there was a problem with my keyboard, but when I pressed the button, the corresponding button in the "Keys" in the simulator also turned black, so it should not be a keyboard problem......

I just want to read the contents of each reference in the Microsoft Programmer's Library CD-ROM (1988) under windows 3.1, but I completely have no idea about what exactly should I do when the desktop turns this.
![5](https://user-images.githubusercontent.com/45331619/106390073-a2070700-6421-11eb-9fb6-305175e74e1c.PNG)

I’m sorry Jeff because I'm not sure if this can be called an issue, but I have tried various methods for nearly a month and no one worked.
I sincerely await your reply, thank you for your reading Jeff.

**Comment by jeffpar** [comment]
MSL.EXE is a terminate-and-stay-resident (TSR) utility that's designed to be run from a COMMAND.COM prompt.  If MSL.EXE is run directly from Windows instead of COMMAND.COM, then the above message is displayed, giving you the chance to activate the TSR before Windows immediately closes it (if you had run COMMAND.COM first, that wouldn't happen).

It sounds like you're not sure what the program hotkey is.  It defaults to LEFT-SHIFT + ALT.  Press and release both those keys at the same time to access MSL's menus.

<img width="898" alt="Screen Shot 2021-01-31 at 11 26 53 AM" src="https://user-images.githubusercontent.com/645749/106395681-684de600-63b8-11eb-8212-9e3e7508287f.png">

**Comment by jeffpar** [comment]
Also, the [blog post](https://www.pcjs.org/blog/2019/05/31/#running-microsoft-programmers-library) has been updated.

**Comment by roundlessx** [comment]
Thank you so much Jeff, everything became normal when I tried your method. Thank you again for this amazing website that you created, and sincerely hope that it will be known by more and more people. ：）

**Comment by IAW9927** [comment]
Bruh. I tried the Cd and it did this: 
![933CDDE0-B877-4B59-B007-937DD2F1177F](https://user-images.githubusercontent.com/78383280/110651785-63cbd880-8181-11eb-89d1-fe10afb5a1da.png)
