### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by DamieFC** [jeffpar/pcjs#14]
This isn't an issue, just a suggestion. I was thinking that it would be cool if there were early Apple PC simulations (Apple II, Macintosh), like how there is for Windows and MS/PC-DOS. It's just an idea. Thank you for considering!

**Comment by IAW9927** [comment]
[Netscape Navigator.zip](https://github.com/jeffpar/pcjs/files/6032244/Netscape.Navigator.zip)
Thanks! I might make a Mac image and send it!!! Then use that Image, my Netscape browser (NEW!) is here in the disk images and use this PCjs Machine to do it: https://www.pcjs.org/machines/pcx86/ibm/5170/vga/cdrom/
And insert Disk 1 and run A:\SETUP.EXE or A:\SETUP.COM
Files may be here.
And don’t forget! Floppy Disk Library is @ 
https://archive.org/details/floppysoftware?&sort=downloads
https://archive.org/details/floppysoftware?&sort=downloads
https://archive.org/details/floppysoftware

**Comment by DamieFC** [comment]
Ok! Thank you for replying!

**Comment by DamieFC** [comment]
(Something tells me I should close this)
