### ISSUE TITLE
Windows 98 & 2000 needs to be added, and those machines with a 512Mb hard disk and 512Mb of RAM, XP with built-in Internet access.

### ISSUE THREAD

**Issue by IAW9927** [jeffpar/pcjs#15]
Pls fix the Windows 95 PCx86 glitch of not rebooting to Windows 95 and not booting from Floppy disk.
And add PCx80 commands with PCx86, and Windows 98/2000/ME/XP demo on your site if you could send me the URL of the thing, I have the following disk images that can be booted for your Windows 1 & 2 machines and a Notepad/1.1 Machine
And add a 486 for Windows 98/2000 and add a Pentium IIII @ 733Mhz CPU for ME & XP. THANKS!!!

**Comment by jeffpar** [comment]
Sorry, but I have no plans to add support for any operating system newer than Windows 95.  My focus now is going back farther in time, not forward in time.

**Comment by IAW9927** [comment]
where is the fix for windows 2.03 386 and Windows 95\386 not rebooting to floppy? how to install dos 6 to it so I can reboot the machine properly?
