### ISSUE TITLE
Windows 3.1 would lock up on Netscape 3.01 Installer with error 423&111

### ISSUE THREAD

**Issue by IAW9927** [jeffpar/pcjs#19]
![82DF7608-0B5B-4608-BB2A-EA6457505CA6](https://user-images.githubusercontent.com/78383280/110539004-51eb2680-80ea-11eb-87b1-9f9d38f6db77.png)

**Comment by DamieFC** [comment]
I think the issue is that Windows 3.1 wasn't made for the internet. Windows 95 was the one with specific Internet support, so try [the Windows 95 machine](https://www.pcjs.org/software/pcx86/sys/windows/win95/4.00.950/)

**Comment by Myron-S** [comment]
Should still work.  I've had MS-DOS connected to the Internet using a text-only browser and a text based e-mail client.

**Comment by DamieFC** [comment]
Huh. Ok. I stand corrected. Maybe try installing a different version of Netscape, or a different browser like Mosaic? Or try using another browser (real) to access PCjs. I don't know, it's just an idea.

**Comment by DamieFC** [comment]
Maybe try a different version of Netscape?

**Comment by IAW9927** [comment]
wait a second, the internet dosent work on that machine

**Comment by jeffpar** [comment]
Adding any level of support for networking in Windows 95 (or Windows 3.x, Windows for Workgroups, etc) would be a large undertaking -- not something I plan to tackle. Sorry.
