### ISSUE TITLE
Windows 3.1 Machine does this.

### ISSUE THREAD

**Issue by IAW9927** [jeffpar/pcjs#20]
<img width="1024" alt="Microsoft Windows 3 10  PCjs Machines" src="https://user-images.githubusercontent.com/78383280/110650808-7c87be80-8180-11eb-97b1-87b4f5110995.png">

**Comment by IAW9927** [comment]
On PCjs v2.07 it said in the browser.

**Comment by Myron-S** [comment]
Try another device.  I've just now tried the same VM on my computer.  My result was .....

![image](https://user-images.githubusercontent.com/23613424/110698356-77a92600-81e5-11eb-9812-4fad199c5a7b.png)

.... so, is the issue running the VM on an Apple iPad?

Also, me not understanding iPads.  Is your device in Air-plane mode or not?

![image](https://user-images.githubusercontent.com/23613424/110698957-349b8280-81e6-11eb-86c8-23235119c763.png)

**Comment by jeffpar** [comment]
It works fine on my iPad.  Checksum messages should only be triggered when the user issues specific debugger commands (eg, 'x'), so I'm going to close this as user error, at least until more information is provided.  Please use caution when using the built-in debugger.

![IMG_0225](https://user-images.githubusercontent.com/645749/110729926-67d51600-81d4-11eb-86e0-562baec5d42e.PNG)
