### ISSUE TITLE
Can't mount external CD-ROM 

### ISSUE THREAD

**Issue by gattilorenz** [jeffpar/pcjs#23]
When using the pcjs machine at https://www.pcjs.org/machines/pcx86/ibm/5170/vga/cdrom/?debugger=true I can't load an external ISO, the error being "FDC: Unrecognized disk format (24338432 bytes)".

It seems the code behind the "mount" button always assumes that the file should be mounted on the floppy drive?

**Comment by IAW9927** [comment]
I tried, it only loads 360K images then it does not show up in the emulator. And try using [Second emulator that works with CD-ROM] (http://copy.sh/v86)

**Comment by jeffpar** [comment]
CD-ROM support for external ISOs is not a feature, either current or planned.  Sorry.
