### ISSUE TITLE
How to compile PCjs in Raspberry Pi / Debian

### ISSUE THREAD

**Issue by IAW9927** [jeffpar/pcjs#26]
Can you give me a guide on how to compile PCjs on Raspberry Pi? I have hosted emulators using the server... and I want the instruction for the compile instructions. And can you give me instructions on how to run the web server in /var/www and then run the PCjs webserver?

**Comment by xandaaah** [comment]
Same and you dont need to run it in /var/www bruh

**Comment by jeffpar** [comment]
See [Running PCjs Locally](https://github.com/jeffpar/pcjs/wiki/Running-PCjs-locally).  That process produces a complete copy of the website in the "_site" folder, which you could then copy to another machine and point the webserver of your choice at it.
