### ISSUE TITLE
Can Windows 95 be connected to the Internet?

### ISSUE THREAD

**Issue by edent** [jeffpar/pcjs#28]
I am aware of the perils of connecting an unpatched Windows installation to the Internet - but I thought it might be fun to try out old versions of Internet Explorer.

Is that possible - or just a very silly idea?

Thanks for the brilliant website.

**Comment by DamieFC** [comment]
I've tried but it always takes forever and nothing ever happens.

**Comment by b3s23love** [comment]
Without a good firewall, a modern supported OS and antivirus, it would be very unsafe and the machine would be hacked in **minutes**.

**Comment by jeffpar** [comment]
Adding any level of support for networking in Windows 95 would be a large undertaking -- not something I plan to tackle.  Sorry.

**Comment by Jacobcallisono1** [comment]
At least there is still INTERNAT
