### ISSUE TITLE
Implement option to switch FPU to 80-bit precision

### ISSUE THREAD

**Issue by ZaDarkSide** [jeffpar/pcjs#29]
You should checkout this link https://hacks.mozilla.org/2014/10/introducing-simd-js/ and
https://blog.mozilla.org/javascript/2015/03/10/state-of-simd-js-performance-in-firefox/
Maybe we could implement most of SSE instructions with SIMD.js and maybe this could also get rid of those floating-point precision errors for normal FPU operations.
And this is the implementation in software/polyfill https://github.com/johnmccutchan/ecmascript_simd/blob/master/src/ecmascript_simd.js until the changes land in the latest browsers.

**Comment by MoochMcGee** [comment]
This emulator barely emulates a 386, let alone a Pentium 3. I don't know
why you're so anxious to implement SSE when the emulator is so early in
development.

**Comment by ZaDarkSide** [comment]
I'm not anxious at all, SSE is an instruction set, the difference between a i386 and a Intel Pentium 1 or AMD equivalent for example is more or less the MMX or 3DNow! instruction set which can be also implemented with SIMD.js.

What really limits an emulator is it's speed not how many instruction sets are implemented. And the speed will get better with time, better Javascript engines, better browsers, better CPUs that can run emulators faster and closer to real speeds.

You can emulate any other processor or hardware if you wanted and Javascript even if it's not the perfect language to write emulators in, it's not keeping you from doing so.

But my suggestion besides implementing more instruction sets, is to emulate a full 80-bit precision FPU instead of a 64-bit precision FPU or present both options in order for you to choose if you want less precision for better performance or vice-versa and because many applications do use them, mainly old 3D games which will suffer from the lost precision in 3D calculations for example.

**Comment by jeffpar** [comment]
PCjs isn't intended to compete with native full-featured emulators.  The intent is to emulate old IBM PCs at their original speeds, with their original ROMs, original hardware, etc, from the 1980's.  Most emulators only emulate more modern hardware (like a VGA video card and ATA disk controller), which means you can't boot with an old IBM PC XT ROM, for example.

I'm pretty much going to stop with the 80386 CPU (and eventually the 80387 FPU).  Admittedly, the 80486 was introduced in 1989, but it didn't add any interesting new features, so I see no reason to go there.  Of course, anyone else is welcome to take it farther, but personally, I'd rather see investments made in improving classic PC hardware emulation.

Speed-wise, I'm already pretty happy with the current level of JavaScript performance, because after all, an IBM PC only ran at 4.77Mhz.  And while it would be nice to have an FPU implementation indistinguishable from the original hardware, virtually no x86 software really cared that much.  Most machines in the 1980's didn't have a coprocessor, so emulation libraries were used instead, and those libraries were rarely more accurate than 64-bit anyway.  And if any 3D games used floating-point, then they were probably from the 1990's, and even then, most games performed their own fixed-point arithmetic and stayed away from floating-point.

**Comment by ZaDarkSide** [comment]
Well there are some applications that cared, mainly games and some demos from the scene.
I'm rather interested in the accuracy of emulation than speed, that's why I'm suggesting that 80-bit precision FPU should be an option.

And to go further than 80386 instruction set and the 80387 FPU is a long-term plan, of course after all the instruction bugs are found and fixed for the current CPU and FPU, basically nobody would mind to see in the end a full-featured Javascript emulator, and contributing to other instruction sets wouldn't hinder the current progress, because of how modular the current system is and how you can opt-in or opt-out for features in the XML configs.

Maybe it is just wishful thinking on my part, but as I said Javascript engines are getting better, we have asm.js for Firefox and Web Workers API, soon SIMD.js in ES7 for accelerating SIMD operations and so on.

I also have a love for old software and classic games and how they were made and many developers used some code tricks to achieve some very nice results, but they require accuracy emulation of the original hardware, but I wouldn't mind to run some more modern applications and operating systems in a browser tab.

**Comment by jeffpar** [comment]
I definitely agree that accuracy of emulation is one of the more important goals, so if there's a not-too-painful path to accurate 80-bit FPU emulation, that sounds worthwhile.  I can't tackle it myself right now, but we'll leave the issue open until somebody does.  ;-)  As for SSE, well, let's consider that a separate issue.

**Comment by mgarlanger** [comment]
Could you provide examples of applications that behave differently in PCjs, vs. a real PC due to differences in the 8087 accuracy? As Jeff pointed out, I'd think any performance critical code would be using fixed-point, since even with the 8087, these instructions were still slow.

**Comment by ZaDarkSide** [comment]
I have change the issue title to better reflect the immediate issue that is addressing.

@mgarlanger Glad you asked, I will compile a list of old software that really uses FPU to 80-bit precision and depend on this feature. Implementing FPU to 80-bit precision will immediately enable doing some math related problems work on PCjs like compiling some old FORTRAN programs that represent some legacy code and run them.

**Comment by ZaDarkSide** [comment]
Some programs that use the FPU:

* CAD programs (AutoCAD, VersaCAD, GenericCAD)
* Spreadsheet programs (Lotus 1-2-3, Excel, Quattro, Wingz)
* Business graphics programs (Arts&Letters, Freedom of Press, Freelance)
* Mathematical analysis and statistical programs (Mathematica, TKSolver, SPSS/PC, Statgraphics)
* Database programs (dBase IV, FoxBase, Paradox, Revelation)

**Comment by Creeper20428** [comment]
I like the idea, but implementing 80-bit floats in JavaScript is easier said than done.

There's plenty of documentation on how 32-bit and 64-bit floats are implemented.
However, the 80-bit format seems to be poorly documented.

Second, it's simple to do
```javascript
st0 = st1 + st2; 
```
and get all the flags (Infinity, NaN, etc.)
But, it would turn into this:
```javascript
st0 = F80.add(st1, st2);
if(F80.isNaN(st0)){ /* NaN flag is on */ }
if(F80.isInfinity(st0){ /* Infinity flag is on */}
```
And there are denormals, "precision", etc.

**Comment by Creeper20428** [comment]
> Intel did "introduce" the 80486 in 1989, but it was more or less unavailable until 1990, and it didn't add any significant new features, so I see no reason to go there.


Well, it would be cool to see OS/2 Warp 4 boot in PCjs, because it needed a "486 or better" to boot.

**Comment by jeffpar** [comment]
I think it's cooler to be able to run OS/2 1.0 personally. ;-)
