### ISSUE TITLE
IBM PC AT Diagnostics 2.07(Adv)

### ISSUE THREAD

**Issue by ChinesePerson001** [jeffpar/pcjs#52]
I am using 86Box and I tried to boot from this disk, and it asked me if a ran this program after the battery has been connected, I typed N and few seconds later it displayed "System Board Error". What should I do? Could you please help me?

**Comment by jeffpar** [comment]
I don't see a problem in PCjs, and I don't work on 86Box.  You'll need to talk to somebody who does.

<img width="791" alt="Screenshot 2022-11-30 at 6 21 00 PM" src="https://user-images.githubusercontent.com/645749/204950412-7c692a3b-19f7-4db6-b6e1-5a65ced38225.png">
