### ISSUE TITLE
Need machine with 8088 processor and Borland Turbo C ...

### ISSUE THREAD

**Issue by rezamarzban** [jeffpar/pcjs#54]
Hi, I need an emulated machine (by PCjs) with:

8088 processor 
and 640kB RAM 
and MS-DOS 3.20 operating system 
and host keyboard, 
And available Borland Turbo C disk images to loading at it. 

Is there anyone can help me?!

PCjs is good, But it is very hard to config manually for individual purposes.

Qemu is easily configurable by entering its arguments in single command line to choosing available CPU model, RAM size, hard drive and so on. But PCjs is not configurable easily to choosing these.
Also PCem and 86Box is easily configurable but consume high system resources.

PCjs doesn't need hight system resources, But it is not configurable easily to choosing CPU model, RAM size, hard drive and so on.

**Comment by rezamarzban** [comment]
I've found it recently! 8086tiny emulator ...

**Comment by jeffpar** [comment]
Fully customizable PCjs machines are a feature for another day, and my time is limited.  For now, what you see is what you get.  Sorry.
