### ISSUE TITLE
can't use while in school

### ISSUE THREAD

**Issue by minefox199** [jeffpar/pcjs#65]
hi it's me again i can access the website because of my school can you make a unblocked version of the website plz that will be much appreciated.

**Comment by Groovzthegameguy** [comment]
Assuming your school doesn't block the Wayback machine, type PCjs.org into the Wayback Machine.
(You may have to click on a link to an archived page from somewhere like Wikipedia to access the Wayback Machine)

**Comment by jeffpar** [comment]
I don't want to get into a game of whack-a-mole.  It would be better if you asked your school why they block the site and if there's something I could do to address it (like creating a smaller version with only specific machines/software).

**Comment by minefox199** [comment]
ok so umm i got done with school for the summer i can go to the page now and yes make a smaller version with windows in it
