### ISSUE TITLE
Windows 95 doesn't boot up.

### ISSUE THREAD

**Issue by Ao28th28thedev** [jeffpar/pcjs#77]
1800's computer moment

**Comment by jeffpar** [comment]
I just tried it (https://www.pcjs.org/software/pcx86/sys/windows/win95/4.00.950/) and it still seems to work fine.

**Comment by Ao28th28** [comment]
JK for other sides than my client

**Comment by Ao28th28** [comment]
> 1800's computer moment

That's because of too much cache or something.
